### ISSUE TITLE
Runtime error

### ISSUE THREAD

**Issue by cbetta** [jasongitmail/fast-webhook#1]
Hi there,

I suddenly am running into an error when using this action. I've made no changes and it doesn't seem like you did either. My gut feeling is that this is a change in the underlying GH Actions infra that broke the feature.

My code:

```yml
      - name: 'Trigger Netlify deployment'
        uses: jasongitmail/fast-webhook@v1
        with:
          url: ${{ secrets.WEBHOOK_URL }}
          json: '{}'
```

The error:

```sh
Current runner version: '2.272.0'
Operating System
  Ubuntu
  18.04.4
  LTS
Virtual Environment
  Environment: ubuntu-18.04
  Version: 20200802.1
  Included Software: https://github.com/actions/virtual-environments/blob/ubuntu18/20200802.1/images/linux/Ubuntu1804-README.md
Prepare workflow directory
Prepare all required actions
Download action repository 'actions/checkout@v2'
Download action repository 's0/git-publish-subdir-action@develop'
Download action repository 'jasongitmail/fast-webhook@v1'
##[error]jasongitmail/fast-webhook/v1/action.yml (Line: 15, Col: 9): Unexpected value ''
##[error]jasongitmail/fast-webhook/v1/action.yml (Line: 15, Col: 9): Unexpected value ''
##[error]System.ArgumentException: Unexpected type 'NullToken' encountered while reading 'outputs'. The type 'MappingToken' was expected.
   at GitHub.DistributedTask.ObjectTemplating.Tokens.TemplateTokenExtensions.AssertMapping(TemplateToken value, String objectDescription)
   at GitHub.Runner.Worker.ActionManifestManager.Load(IExecutionContext executionContext, String manifestFile)
##[error]Fail to load jasongitmail/fast-webhook/v1/action.yml
```

**Comment by bloerwald** [comment]
The error is on github's side apparently, with `outputs:` previously being "none" and now being an error. The fix is as simple as it is stupid: https://github.com/bloerwald/fast-webhook/commit/07ed22096fc77243fb0644ec9e23835c24081e6f

**Comment by jasongitmail** [comment]
Thanks for the issue. I've merged the PR. Will put out a new release

**Comment by jasongitmail** [comment]
I pushed a new release with the fix. 

It's still under v1 major version so using `uses: jasongitmail/fast-webhook@v1` still works. Thanks again!
